name: Subscription Share
labels: [subscription, share]
body:
  - type: markdown
    attributes:
      value: |
        ## 📝 Share Your Subscription Experience
        Thank you for sharing! Your experience can help other users make better choices.

  - type: input
    id: service-name
    attributes:
      label: Service Name
      description: Name of the subscription service you want to share
      placeholder: e.g., Netflix, Spotify, ChatGPT Plus
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select service category
      options:
        - Streaming
        - Software
        - Cloud Storage
        - Music
        - Design
        - Fitness
        - Education
        - Gaming
        - Other
    validations:
      required: true

  - type: input
    id: price
    attributes:
      label: Price
      description: Please specify currency and billing cycle
      placeholder: e.g., $15.49/month, ¥68/month
    validations:
      required: true

  - type: dropdown
    id: rating
    attributes:
      label: Overall Rating
      description: Your overall rating for this service
      options:
        - '⭐⭐⭐⭐⭐ (5/5) - Highly Recommended'
        - '⭐⭐⭐⭐ (4/5) - Recommended'
        - '⭐⭐⭐ (3/5) - Average'
        - '⭐⭐ (2/5) - Not Recommended'
        - '⭐ (1/5) - Strongly Not Recommended'
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: Experience
      description: Share your detailed experience
      placeholder: |
        - Why you subscribed to this service
        - Primary use cases
        - Frequency of use
        - Whether it met your expectations
    validations:
      required: true

  - type: textarea
    id: pros
    attributes:
      label: Pros
      description: Advantages of this service
      placeholder: |
        - Pro 1
        - Pro 2
        - Pro 3
    validations:
      required: true

  - type: textarea
    id: cons
    attributes:
      label: Cons
      description: Disadvantages of this service
      placeholder: |
        - Con 1
        - Con 2
        - Con 3
    validations:
      required: true

  - type: textarea
    id: recommendation
    attributes:
      label: Recommendation
      description: Who would you recommend this to?
      placeholder: |
        Suitable for: Designers, students, power users...
        Not suitable for: Light users, budget-conscious users...

  - type: input
    id: promo-code
    attributes:
      label: Promo Code (Optional)
      description: Share a promo code if available
      placeholder: e.g., SAVE30

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: The information I provide is true and accurate
          required: true
        - label: I agree to follow the Code of Conduct
          required: true
